apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  SENTRY_DSN: https://4564f9e9570f4f57a9055453dcba0adf@o473402.ingest.sentry.io/5508276
  ENVIRONMENT: production
  ALLOWED_HOST: "*"
