# Generated by Django 3.1.3 on 2020-11-29 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sentence', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('fr', 'fr'), ('en', 'en')], default='fr', max_length=10)),
                ('status', models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE'), ('BLACKLISTED', 'BLACKLISTED')], default='INACTIVE', max_length=12)),
            ],
            options={
                'unique_together': {('sentence', 'language')},
            },
        ),
    ]
