# Generated by Django 3.1.3 on 2020-11-29 08:48

from django.db import migrations


def copy_old_suggestions(apps, _schema_editor):
    OldSuggestion = apps.get_model("core", "Suggestion")
    NewSuggestion = apps.get_model("suggestions", "Suggestion")

    new_suggestions = []
    for old_suggestion in OldSuggestion.objects.all():
        new_suggestion = NewSuggestion(
            sentence=old_suggestion.sentence,
            language=old_suggestion.language,
            status=old_suggestion.status,
            created_at=old_suggestion.created_at,
            updated_at=old_suggestion.updated_at,
        )
        new_suggestions.append(new_suggestion)

    NewSuggestion.objects.bulk_create(new_suggestions)


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0001_initial"),
        ("core", "0031_refactor_suggestions")
    ]

    operations = [
        migrations.RunPython(
            code=copy_old_suggestions, reverse_code=migrations.RunPython.noop
        )
    ]
