# Generated by Django 3.1.5 on 2021-01-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_copy_suggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='language',
            field=models.CharField(choices=[('fr', 'fr'), ('en', 'en'), ('de', 'de')], default='fr', max_length=10),
        ),
    ]
