Description: PasseUnDessin Api - ECR Repositories

Parameters:
  PasseUnDessinApiRepositoryName:
    Type: String
    Default: job4/api
  Env:
    Type: String
    Default: staging

Resources:
  PasseUnDessinApiRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: !Sub ${PasseUnDessinApiRepositoryName}-${Env}

Outputs:
  PasseUnDessinApiRepository:
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${PasseUnDessinApiRepositoryName}-${Env}
  PasseUnDessinApiRepositoryName:
    Value: !Sub ${PasseUnDessinApiRepositoryName}-${Env}
