AWSTemplateFormatVersion: "2010-09-09"
Description: PasseUnDessin database - PostgreSQL
Parameters:
  Env:
    Description: The environment name deployed
    Type: String
    Default: staging
  DBInstanceClass:
    Type: String
    Default: "db.t2.small"
  DBPassword:
    Type: String
    NoEcho: True

Resources:
  MasterInstance:
    Properties:
      AllocatedStorage: 20 # In Gigabytes
      DBInstanceIdentifier: !Sub postgres-${Env}
      DBName: job4db
      DBInstanceClass:
        Ref: DBInstanceClass
      StorageType: "gp2"
      Engine: "postgres"
      EngineVersion: "11.5"
      MasterUsername: "job4"
      MasterUserPassword:
        Ref: DBPassword
      PubliclyAccessible: true
      DeletionProtection: true
    Type: AWS::RDS::DBInstance

Outputs:
  DatabaseHostname:
    Value: !GetAtt MasterInstance.Endpoint.Address
  DatabasePort:
    Value: !GetAtt MasterInstance.Endpoint.Port
