# Generated by Django 3.1.4 on 2020-12-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='twitch_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='twitch_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
