# Generated by Django 3.1.4 on 2020-12-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0002_twitch_id_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='polling',
            name='stacktrace',
            field=models.TextField(blank=True, null=True),
        ),
    ]
