AWSTemplateFormatVersion: "2010-09-09"

Description: PasseUnDessin front - Creation of S3 bucket

Parameters:
  FrontBucketName:
    Type: String
    Description: S3 bucket name
    Default: passe-un-dessin-front

  Env:
    Description: The environment name deployed
    Type: String

Resources:
  FrontBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${FrontBucketName}-${Env}
      Tags:
        - Key: Project
          Value: PasseUnDessinFront
        - Key: Env
          Value: !Ref Env
      WebsiteConfiguration:
        IndexDocument: index.html
      AccessControl: PublicRead
      VersioningConfiguration:
        Status: Enabled
  S3PolicyFrontBucket:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - !Ref FrontBucket
                  - "/*"

Outputs:
  FrontS3Bucket:
    Value: !Ref FrontBucket
