# Generated by Django 3.0.4 on 2020-03-28 22:02

import core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200328_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(choices=[(core.models.GamePhase['INIT'], 'Initialization'), (core.models.GamePhase['ROUNDS'], 'Rounds'), (core.models.GamePhase['DEBRIEF'], 'Debrief')], default='INIT', max_length=10)),
                ('current_round', models.IntegerField(null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='core.Room')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pad',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pads', to='core.Game')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='player',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='core.Room'),
        ),
        migrations.CreateModel(
            name='PadStep',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_type', models.CharField(choices=[(core.models.StepType['WORD_TO_DRAWING'], 'Word to Drawing'), (core.models.StepType['DRAWING_TO_WORD'], 'Drawing to Word')], max_length=20)),
                ('round_number', models.IntegerField()),
                ('sentence', models.CharField(blank=True, max_length=100, null=True)),
                ('drawing', models.CharField(blank=True, max_length=10000, null=True)),
                ('pad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.Pad')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Player')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pad',
            name='initial_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Player'),
        ),
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='core.Game'),
        ),
        migrations.AddField(
            model_name='room',
            name='current_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_as_current_game', to='core.Game'),
        ),
    ]
