# Generated by Django 3.0.4 on 2020-03-28 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200328_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='core.Room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='core.Game'),
        ),
        migrations.AlterField(
            model_name='player',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='core.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='current_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_as_current_game', to='core.Game'),
        ),
    ]
