# Generated by Django 3.0.4 on 2020-03-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200328_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='pad',
            name='sentence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
