# Generated by Django 3.0.4 on 2020-04-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pad_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padstep',
            name='drawing',
            field=models.TextField(blank=True, null=True),
        ),
    ]
