# Generated by Django 3.0.5 on 2020-04-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200404_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='color',
            field=models.CharField(default='#9337AE', max_length=10),
            preserve_default=False,
        ),
    ]
