# Generated by Django 3.0.5 on 2020-04-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_player_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='round_duration',
            field=models.IntegerField(default=60),
        ),
    ]
