# Generated by Django 3.0.5 on 2020-05-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200427_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='draw_own_word',
            field=models.BooleanField(default=True),
        ),
    ]
