# Generated by Django 3.0.5 on 2020-05-08 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_room_friendly_name'),
        ('core', '0019_game_draw_own_word'),
    ]

    operations = [
    ]
