# Generated by Django 3.0.5 on 2020-07-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_merge_20200508_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pad',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='padstep',
            options={'ordering': ('round_number',)},
        ),
    ]
