# Generated by Django 3.0.8 on 2020-07-26 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_game_player_manytomany'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='player',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='core.Player'),
        ),
    ]
