# Generated by Django 3.0.8 on 2020-10-06 20:44

from django.db import migrations


def forward(apps, schema_editor):
    Player = apps.get_model("core", "Player")
    for player in Player.objects.all():
        first_participation = player.participations.order_by(
            "game__created_at"
        ).first()
        if not first_participation:
            continue
        first_game_created_at = first_participation.game.created_at
        if first_game_created_at < player.created_at:
            player.created_at = first_game_created_at
            player.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_rebuild_player_game_participation"),
    ]

    operations = [
        migrations.RunPython(forward, reverse_code=migrations.RunPython.noop)
    ]
