# Generated by Django 3.0.8 on 2020-10-24 12:02

from django.db import migrations

query = """
UPDATE core_playergameparticipation
SET
    created_at = core_game.created_at,
    updated_at = core_game.updated_at
FROM core_game
WHERE core_playergameparticipation.game_id = core_game.uuid;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_fix_player_created_at"),
    ]

    operations = [migrations.RunSQL(query, reverse_sql=migrations.RunSQL.noop)]
