# Generated by Django 3.1.2 on 2020-10-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_fix_playergameparticipation_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="avatar",
            field=models.TextField(blank=True, null=True),
        ),
    ]
