# Generated by Django 3.1.3 on 2020-11-24 21:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20201114_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sentence', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sentence', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=10)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'unique_together': {('sentence', 'language')},
            },
        ),
    ]
