# Generated by Django 3.1.3 on 2020-11-26 12:19

from django.db import migrations, models

import core.models


def migrate_status(apps, schema_editor):
    Suggestion = apps.get_model("core", "Suggestion")
    Suggestion.objects.filter(is_active=True).update(status="ACTIVE")
    Suggestion.objects.filter(is_active=False).update(status="INACTIVE")


def add_blacklisted_suggestions(apps, schema_editor):
    Suggestion = apps.get_model("core", "Suggestion")
    BlackList = apps.get_model("core", "BlackList")
    suggestions_to_create = [
        Suggestion(language="fr", status="BLACKLISTED", sentence=blacklist.sentence)
        for blacklist in BlackList.objects.all()
    ]
    Suggestion.objects.bulk_create(suggestions_to_create)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_blacklist_suggestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestion",
            name="status",
            field=models.CharField(
                choices=[
                    ("INACTIVE", "INACTIVE"),
                    ("ACTIVE", "ACTIVE"),
                    ("BLACKLISTED", "BLACKLISTED"),
                ],
                default="INACTIVE",
                max_length=30,
            ),
        ),
        migrations.RunPython(migrate_status, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="suggestion",
            name="is_active",
        ),
        migrations.RunPython(
            add_blacklisted_suggestions, reverse_code=migrations.RunPython.noop
        ),
        migrations.DeleteModel(
            name="BlackList",
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="language",
            field=models.CharField(
                choices=[("fr", "fr"), ("en", "en")],
                default="FR",
                max_length=10,
            ),
        ),
    ]
