# Generated by Django 3.1.3 on 2020-11-27 19:20

from django.db import migrations, models

import core.models


def migrate_total_score(apps, schema_editor):
    Player = apps.get_model("core", "Player")
    players = Player.objects.annotate(
        computed_total_score=models.Count("steps__votes")
    )
    for player in players:
        player.total_score = player.computed_total_score
        player.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_refactor_suggestions"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="total_score",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(
            migrate_total_score, reverse_code=migrations.RunPython.noop
        ),
    ]
