# Generated by Django 3.1.3 on 2020-11-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_delete_suggestion'),
        ('core', '0032_player_total_score'),
    ]

    operations = [
    ]
