# Generated by Django 3.1.3 on 2020-11-29 21:33

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_player_total_score"),
    ]

    operations = [UnaccentExtension()]
