# Generated by Django 3.1.5 on 2021-01-08 11:34

from django.db import migrations, models


def add_init_padsteps(apps, schema_editor):
    Pad = apps.get_model("core", "Pad")
    PadStep = apps.get_model("core", "PadStep")

    i = 0
    for pad in Pad.objects.all():
        i += 1
        if i % 100 == 0:
            print(i)
        PadStep.objects.create(
            pad=pad,
            round_number=0,
            step_type="INITIAL",
            sentence=pad.sentence,
            player=pad.initial_player,
        )


def remove_init_padsteps(apps, schema_editor):
    PadStep = apps.get_model("core", "PadStep")

    PadStep.objects.filter(step_type="INITIAL").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_add_unaccent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="padstep",
            name="step_type",
            field=models.CharField(
                choices=[
                    ("INITIAL", "INITIAL"),
                    ("WORD_TO_DRAWING", "WORD_TO_DRAWING"),
                    ("DRAWING_TO_WORD", "DRAWING_TO_WORD"),
                ],
                max_length=50,
            ),
        ),
        migrations.RunSQL(
            sql="UPDATE core_padstep SET round_number = round_number + 1;",
            reverse_sql="UPDATE core_padstep SET round_number = round_number - 1;",
        ),
        migrations.RunPython(
            code=add_init_padsteps, reverse_code=remove_init_padsteps
        ),
    ]
