# Generated by Django 3.1.5 on 2021-01-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_migrate_initial_steps'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='padstep',
            unique_together={('pad', 'round_number')},
        ),
    ]
