# Generated by Django 3.1.5 on 2021-01-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20210108_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='phase',
            field=models.CharField(choices=[('INIT', 'INIT'), ('ROUNDS', 'ROUNDS'), ('DEBRIEF', 'DEBRIEF'), ('VOTE_RESULTS', 'VOTE_RESULTS')], default='ROUNDS', max_length=12),
        ),
    ]
