# Generated by Django 3.1.5 on 2021-01-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20210108_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pad',
            name='initial_player',
        ),
        migrations.RemoveField(
            model_name='pad',
            name='sentence',
        ),
    ]
