# Generated by Django 3.1.5 on 2021-01-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20210108_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='padstep',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='padstep',
            index=models.Index(fields=['is_featured'], name='padstep_is_featured_idx'),
        ),
    ]
