# Generated by Django 3.1.5 on 2021-01-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_create_is_featured_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='phase',
            field=models.CharField(choices=[('INIT', 'INIT'), ('ROUNDS', 'ROUNDS'), ('REVEAL', 'REVEAL'), ('DEBRIEF', 'DEBRIEF'), ('VOTE_RESULTS', 'VOTE_RESULTS')], default='ROUNDS', max_length=12),
        ),
    ]
