# Generated by Django 3.1.5 on 2021-01-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20210110_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='controlled_reveal',
            field=models.BooleanField(default=False),
        ),
    ]
