# Generated by Django 3.1.7 on 2021-03-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_game_controlled_reveal'),
    ]

    operations = [
        migrations.AddField(
            model_name='padstep',
            name='drawing_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
