# Generated by Django 3.1.7 on 2021-03-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_add_drawing_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergameparticipation',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
