# Generated by Django 3.1.7 on 2021-03-22 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_playergameparticipation_vote_count"),
    ]

    operations = [
        migrations.RemoveField(model_name="padstep", name="drawing",),
        migrations.RemoveField(model_name="player", name="avatar",),
    ]
